name: "Commit Message Check"

on:
  push:
    branches:
      - "**"

jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Commit Messages
        run: |
          IFS=$'\n' commits=($(git log --pretty="%s" --no-merges ${{ github.event.before }}..${{ github.event.after }}))
          for commit in "${commits[@]}"
          do
            if ! [[ "$commit" =~ ^(feat|fix|chore|docs|style|refactor|perf|test)(\(.*\))?:\ .+ ]]; then
              echo "Invalid commit message: $commit"
              exit 1
            fi
          done
