name: Terraform Versioning

on:
  push:
    branches:
      - main # or whichever branch you consider to be your 'main' branch

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate version number
        id: calculate-version
        run: echo "::set-output name=version::$(date +'%Y.%m.%d.%H.%M.%S')"

      - name: Tag repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ steps.calculate-version.outputs.version }}
          git push --tags
